### ISSUE TITLE
Back | Task

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#16]
#### Task implements entity, which provides cyclically (by event) executing calculations
- [x] executed in the cycle mode (current impl) - coming as a "cycle" parameter from the configuration. Zero value or if parameter absent meaning the event mode.
- [x] executed in event mode (if sycle is 0 or not specified)
- [x] has a number of functions / variables / metrics or additional entities

#### consists of
- [x] Task it self - basically the thread, looping with the constant time 
- [x] TaskNodes - holds HashMap<TaskNode> in the following structure:
  ```
  TaskNodes {
       inputName1: TaskEvalNode {...},
       inputName1: TaskEvalNode {...},
  }
  ```
- [x] TaskEvalNode - Holds Task input and all dipendent variables & outputs:
  ```
  TaskEvalNode {
      input: FnInOutRef,
      outs: [
          var1
          var2
          var...
          metric1
          metric2
          metric...
      ]
  }
  ```
  - [x] TaskCycle - provides exact time interval in milles / micros  
     - [x] creates with Duration of interval
     - [x] method start() - begins countdown
     - [x] method wait() - awaiting remainder of the specified interval if not elapsed

  - [x] PushToQueue - kinde of function, on calling eval() or out() copies input value into the associated queue  
     - [x] holds a reference to the associated queue
     - [x] don't chanches input values.

  - [x] FnInOut.eval()  
     - [x] FnInOut.eval() - evaluates al calculations, but nothing returns
     - [x] FnInOut.out() - don't evaluates calculations, just returns already calculated result
  - [ ] #23
